version: "2.2"

services:
  posit-lmod:
    image: mmayer123/posit-lmod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PWB_VERSION: ${PWB_VERSION:-2024.12.0-463.pro4}
        PCT_VERSION: ${PCT_VERSION:-2024.11.0}
    container_name: posit
    hostname: posit
    privileged: true
    volumes:
      - home:/home
    expose:
      - "8787"
      - "3939"
    ports:
      - "8787:8787"
      - "3939:3939"
    environment:
      PCT_LICENSE: ${PCT_LICENSE}

volumes:
  home: 